### ISSUE TITLE
希望尽快解决延时问题

### ISSUE THREAD

**Issue by MarcusPierce** [Haojen/raycast-Parrot#1]
少数派来的，已经用 Parrot 代替 Raycast 默认翻译了，希望多优化优化速度，正好能填补 Bob 查询单词释义不全的空缺，加油！

**Comment by Haojen** [comment]
@MarcusPierce 感谢反馈，这两天安排上。

**Comment by Haojen** [comment]
@MarcusPierce 汇报一下，已经对速度进行了优化目前正在自测中，很快就能提交新版本了

**Comment by thedavidweng** [comment]
> @MarcusPierce 汇报一下，已经对速度进行了优化目前正在自测中，很快就能提交新版本了

[期待的搓手]

**Comment by Haojen** [comment]
@MarcusPierce @thedavidweng The new version is waiting to merge, I think will be soon. https://github.com/raycast/extensions/pull/1678

**Comment by thedavidweng** [comment]
> @MarcusPierce @thedavidweng The new version is waiting to merge, I think will be soon. [raycast/extensions#1678](https://github.com/raycast/extensions/pull/1678)

incredible, good works

**Comment by Haojen** [comment]
@MarcusPierce @thedavidweng The PR is merged. 大家可以尝试看看
